title: Minimal Architect Theme
logo: /assets/img/logo.png
description: Minimal Architect is a theme for GitHub Pages based on Minimal theme.
show_downloads: true
project_wiki: https://google.com
project_issues: https://google.com
google_analytics:
theme: minimal-architect
