title: Minimal Architect Theme
logo: /assets/img/logo.png
description: Minimal Architect is a theme for GitHub Pages based on Minimal theme.
show_downloads: true
project_wiki: https://google.com
project_issues: https://google.com
google_analytics:
theme: minimal-architect
menu:
  - menu-label: User Needs
    menu-url: /user-needs
  - menu-label: Requirements & Constraints
    menu-url: /requirements
  - menu-label: Acceptance Tests
    menu-url: /acceptance-tests
  - menu-label: Implementation(s)
    menu-url: /implementation
  - menu-label: Components Diagrams
    menu-url: /components
  - menu-label: Data & Interaction Models
    menu-url: /models
